version: '3.7'

services:
  autenticacao:
    build: .
    ports:
      - 3000:3000
    volumes:
      - /usr/src/app/node_modules
      - ./:/usr/src/app
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
